RaoVat/Areas/Admin/Controllers/AdminNewsController.cs
using RaoVat.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RaoVat.Areas.Admin.Controllers
{
    public class AdminNewsController : Controller
    {
        RaoVatModel db = new RaoVatModel();
        public string ConvertImage(byte[] imageBrand)
        {
            string base64string = Convert.ToBase64String(imageBrand);
            return "data:image/jpg;base64," + base64string;
        }
        // GET: Admin/AdminNews
        [Authorize(Roles ="Admin")]
        public ActionResult Index()
        {
            return View(db.News.Where(x=>x.Status==0).ToList());
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Detail(string IDNews)
        {
            return View(db.News.Where(x => x.IDNews == IDNews).FirstOrDefault());
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult ImgNews(string IDNews)
        {
            List<ImgNews> list = db.ImgNews.Where(x => x.IDNews == IDNews).ToList();
            foreach(var item in list)
            {
                item.Image =item.ImgURL;
            }
            return PartialView(list);
        }
        public JsonResult Agree(string IDNews)
        {
            News news = db.News.Where(x => x.IDNews == IDNews).FirstOrDefault();
            news.Status = 2;
            db.Entry(news).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            string msg = "Tin đã được duyệt";
            return Json(msg,JsonRequestBehavior.AllowGet);
        }
        public JsonResult Denine(string IDNews)
        {
            News news = db.News.Where(x => x.IDNews == IDNews).FirstOrDefault();
            news.Status = 1;
            db.Entry(news).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            string msg = "Tin đã bị từ chối";
            return Json(msg,JsonRequestBehavior.AllowGet);
        }
    }
}

RaoVat/Areas/Admin/Views/AdminNews/Detail.cshtml
@model RaoVat.Models.News
@using System.Globalization;
@{
    ViewBag.Title = "Detail";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<style>
    h1, p {
        color: black;
    }

    b {
        color: #419A1C;
    }

    .btn {
        flex: 1;
        line-height: 2rem;
       
    }
</style>

<div class="product__info-body" id="body-info">
    <h1><b>Thông Tin Tin Rao</b></h1>
    <div class="grid__row" style="padding-bottom: 12px;">
        <div class="grid__column-8">
            <div class="product__info-detail">
                <h1 class="description__header"><b>Tài Khoản Đăng Tin:</b> @Html.DisplayFor(model => model.Users.UserName, new { @class = "description__header" }) </h1>
                <h1 class="description__header"><b>Hình Ảnh</b></h1>
                <div class="product__info-sliderImg">
                    @{Html.RenderAction("ImgNews", "AdminNews", new { IDNews = Model.IDNews });}
                </div>
                <div class="product__info-description">

                    <h1 class="description__header"><b>Tên Tin Rao:</b> @Html.DisplayFor(model => model.Name, new { @class = "description__header" }) </h1>
                    <div class="description__price-current">
                        @{ CultureInfo culture = new CultureInfo("vi-VN"); }
                        <p> <b>Giá: </b>  @String.Format(culture, "{0:N0}", Model.Price) VNĐ</p>
                    </div>
                    <div class="description__detail">
                        <h1 class="description__header"><b>Mô Tả Tin Rao:</b></h1>
                        <p class="description__detail-text">
                            @Html.DisplayFor(model => model.Description)
                        </p>
                    </div>
                    <div>
                        <h1 class="description__header">
                            <b>Loại Hình Kinh Doanh:</b>
                            @if (Model.Type == false)
                            {
                                <span>Cá Nhân</span>
                            }
                            else
                            {
                                <span>Cửa Hàng</span>
                            }
                        </h1>
                    </div>
                    <div style=" display: flex; justify-content: space-between;">
                        <h1 class="description__header">
                            <b>Danh Mục: </b> @Html.DisplayFor(model => model.Brand.SubCategory.Category.Name)
                        </h1>
                        <h1 class="description__header">
                            <b>Danh Mục Con: </b>  @Html.DisplayFor(model => model.Brand.SubCategory.Name)
                        </h1>
                        <h1 class="description__header">
                            <b>Dòng: </b>  @Html.DisplayFor(model => model.Brand.Name)
                        </h1>
                    </div>
                    <div>
                        <h1 class="description__header"><b>Thời Gian Đăng: </b>  @Html.DisplayFor(model => model.Time)</h1>
                    </div>
                </div>
                <div style="display:flex;justify-content:center;">
                    <a onclick="Agree('@Model.IDNews')" class="btn btn-success" style="background: #419A1C;margin-right:8px; ">Duyệt</a>
                    <a onclick="Denine('@Model.IDNews')" class="btn btn-danger" style="margin-left:8px;">Từ chối</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="message-success" id="msg1" style="display:none;opacity:1;">
    <strong><span class="glyphicon glyphicon-ok"></span>Tin đã được duyệt</strong>
</div>
<div class="message-error" id="msg2" style="display:none;opacity:1;">
    <strong><span class="glyphicon glyphicon-ok"></span>Tin đã bị từ chối</strong>
</div>
<script>

    function Agree(IDNews) {      
        $.ajax({
            type: "post",
            url: "/AdminNews/Agree",
            data: { 'IDNews': IDNews },
            success: function () {
                $('#msg1').show();
                $('#body-info').hide();
            }
        })
    }
    function Denine(IDNews) {
        $.ajax({
            type: "post",
            url: "/AdminNews/Denine",
            data: { 'IDNews': IDNews },
            success: function () {
                $('#msg2').show();
                $('#body-info').hide();
            }
        })
    }
</script>

RaoVat/Areas/Admin/Views/AdminNews/Index.cshtml
@model IEnumerable<RaoVat.Models.News>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Tin rao chờ duyệt</h2>

<table class="table">
    <tr>
        <th>
            Mã Tin Rao
        </th>
        <th>
            Người Đăng
        </th>
        <th>
           Thời Gian
        </th>
        <th>
           Loại Hình Kinh Doanh
        </th>
        <th>
           Tên Tin Rao
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IDNews)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Users.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Time)
        </td>
        <td>
            @if (item.Type == false)
            {
                <span>Cá Nhân</span>  
            }
            else
            {
                <span>Cửa Hàng</span >
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Xem Chi Tiết", "Detail", new { IDNews = item.IDNews })   
        </td>
    </tr>
}

</table>