RaoVat/Models/BoxSave.cs
namespace RaoVat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("BoxSave")]
    public partial class BoxSave
    {
        [Key]
        [StringLength(10)]
        public string IDBoxSave { get; set; }

        [StringLength(20)]
        public string IDUser { get; set; }

        [StringLength(20)]
        public string IDNews { get; set; }

        public virtual News News { get; set; }

        public virtual Users Users { get; set; }

        [NotMapped]
        public string IDNewsCurrent { get; set; }

        [NotMapped]
        public string Image { get; set; }
    }
}

RaoVat/Controllers/NewsController.cs
using RaoVat.Common;
using RaoVat.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RaoVat.Controllers
{
    [Route("News/InfoNews")]
    public class NewsController : Controller
    {
        RaoVatModel db = new RaoVatModel();
        // GET: News
        public string ConvertImage(byte[] imageBrand)
        {
            string base64string = Convert.ToBase64String(imageBrand);
            return "data:image/jpg;base64," + base64string;
        }
        public ActionResult Index()
        {
            return View();
        }
        [Route("/{IDNews}")]
        public ActionResult InfoNews(string IDNews)
        {
            if (IDNews != null)
            {
                News news = db.News.Where(x => x.IDNews == IDNews && x.Status==2).FirstOrDefault();
                Users user = db.Users.Where(x => x.IDUser == news.IDUser).FirstOrDefault();
                if (user.Avatar != null)
                {
                    news.Users.Image = ConvertImage(user.Avatar);
                }
                else
                {
                    news.Users.Image = "/Asset/img/user.png";
                }
                return View(news);
            }
            return RedirectToAction("Index","Home");
        }
        public ActionResult ListNewsSame(News model)
        {
            if (model.IDNews != null)
            {
                IEnumerable<News> news = db.News.Where(x => x.Brand.IDSubCategory == model.Brand.IDSubCategory && x.IDNews != model.IDNews && x.Status==2).ToList();
                if (news.ToList().Count > 5)
                {
                    news = news.Take(5);
                }
                foreach (var item in news)
                {
                    if (item.Users.Avatar != null)
                    {
                        item.Users.Image = ConvertImage(item.Users.Avatar);
                    }
                    else
                    {
                        item.Users.Image = "./Asset/img/user.png";
                    }
                    ImgNews imgNews = db.ImgNews.Where(x => x.IDNews == item.IDNews).FirstOrDefault();
                    item.Image = imgNews.ImgURL;
                }
                return PartialView(news);
            }
            return RedirectToAction("Index", "Home");
        }
        [ChildActionOnly]
        public ActionResult ImgNews(string IDNews)
        {
            List<ImgNews> imgNews = db.ImgNews.Where(x => x.IDNews == IDNews).ToList();
            foreach(var item in imgNews)
            {
                item.Image = item.ImgURL;
            }
            return PartialView(imgNews);
        }
        [ChildActionOnly]
        [HttpGet]
        public ActionResult NewsOfOtherUser(string IDUser)
        {
            List<News> news = db.News.Where(x => x.IDUser == IDUser && x.Status == 2).ToList();
            foreach (var item in news)
            {
                ImgNews imgNews = db.ImgNews.Where(x => x.IDNews == item.IDNews).FirstOrDefault();
                item.Image = imgNews.ImgURL;
            }
            return PartialView(news);
        }
        [HttpGet]

        public ActionResult newsOfUser()
        {
            if (Session[CommonConstants.USER_SESSION] != null)
            {
                UserSession User = (UserSession)Session[CommonConstants.USER_SESSION];
                List<News> news = db.News.Where(x => x.IDUser == User.User_ID && x.Status == 2).ToList();
                foreach (var item in news)
                {
                    ImgNews imgNews = db.ImgNews.Where(x => x.IDNews == item.IDNews).FirstOrDefault();
                    item.Image = imgNews.ImgURL;
                }
                return PartialView(news);
            }
            return RedirectToAction("Index", "Home");
        }
        [HttpGet]

        public ActionResult newsRefuse()
        {
            if (Session[CommonConstants.USER_SESSION] != null)
            {
                UserSession User = (UserSession)Session[CommonConstants.USER_SESSION];
                List<News> news = db.News.Where(x => x.IDUser == User.User_ID && x.Status == 1).ToList();
                foreach (var item in news)
                {
                    ImgNews imgNews = db.ImgNews.Where(x => x.IDNews == item.IDNews).FirstOrDefault();
                    item.Image = imgNews.ImgURL;
                }
                return PartialView(news);
            }
            return RedirectToAction("Index", "Home");
        }
        public ActionResult LoadNewsBySearch(List<News> news,double min,double max,string IDCategory,string IDSubCategory,string IDBrand)
        {
            if (news == null && IDCategory==null && IDSubCategory == null && IDBrand==null )
            {
                news = db.News.Where(x => x.Price >= min && x.Price <= max && x.Status==2).ToList();
              
            }else if (news == null && IDCategory != null)
            {
                news = db.News.Where(x =>x.Price >= min && x.Price <= max && x.Brand.SubCategory.IDCategory==IDCategory && x.Status == 2).ToList();
            }
            else if (news == null && IDBrand != null)
            {
                news = db.News.Where(x => x.Price >= min && x.Price <= max && x.Brand.Name == IDBrand && x.Status == 2).ToList();
            }
            else 
            {
                news = db.News.Where(x => (x.Price >= min && x.Price <= max) && x.Brand.IDSubCategory == IDSubCategory && x.Status == 2).ToList();
            }        
            foreach (var item in news)
            {
                if (item.Users.Avatar != null)
                {
                    item.Users.Image = ConvertImage(item.Users.Avatar);
                }
                else
                {
                    item.Users.Image = "./Asset/img/user.png";
                }
                ImgNews imgNews = db.ImgNews.Where(x => x.IDNews == item.IDNews).FirstOrDefault();
                item.Image = imgNews.ImgURL;
            }
            return PartialView(news);
        }
        public ActionResult LoadSubCate(string IDCategory)
        {
            List<SubCategory> model = db.SubCategory.Where(x => x.IDCategory == IDCategory).ToList();
            foreach (var item in model)
            {
                item.Image = ConvertImage(item.ImageSubCate);
            }
            return PartialView(model);
        }
        public ActionResult LoadBrand(string IDSubCategory)
        {
            List<Brand> model = db.Brand.Where(x => x.IDSubCategory == IDSubCategory).ToList();
            foreach (var item in model)
            {
                item.Image = ConvertImage(item.ImageBrand);
            }
            return PartialView(model);
        }
    }
}

RaoVat/Controllers/UserProfileController.cs
using RaoVat.Common;
using RaoVat.DAO;
using RaoVat.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using System.Threading.Tasks;
using RaoVat.Context;

namespace RaoVat.Controllers
{
    [HandleError]
    public class UserProfileController : Controller
    {
        RaoVatModel db = new RaoVatModel();

        public string ConvertImage(byte[] imageBrand)
        {
            string base64string = Convert.ToBase64String(imageBrand);
            return "data:image/jpg;base64," + base64string;
        }
        // GET: UserProfile
        [HttpGet]
        public ActionResult Index()
        {
            if (Session[CommonConstants.USER_SESSION] != null)
            {
                UserSession User = (UserSession)Session[CommonConstants.USER_SESSION];
                Users user = db.Users.Where(x => x.IDUser == User.User_ID).FirstOrDefault();
                if (user.Avatar == null)
                {
                    user.Image = "./Asset/img/user.png";
                }
                else
                {
                    user.Image = ConvertImage(user.Avatar);
                }
                return View(user);
            }

            return RedirectToAction("Index","UserLogin");
        }
        [HttpGet]
        public ActionResult InfoOtherUser(string IDNews)
        {
            if(IDNews!=null)
            {
                var news = db.News.Where(x => x.IDNews == IDNews).FirstOrDefault();
                Users user = db.Users.Where(x => x.IDUser == news.IDUser).FirstOrDefault();
                if (user.Avatar == null)
                {
                    user.Image = "./Asset/img/user.png";
                }
                else
                {
                    user.Image = ConvertImage(user.Avatar);
                }
                return View(user);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
       
        }
      
        [HttpGet]
        public ActionResult Editinfo()
        {
            if (Session[CommonConstants.USER_SESSION] != null)
            {
                
                    UserSession User = (UserSession)Session[CommonConstants.USER_SESSION];
                    Users user = db.Users.Where(x => x.IDUser == User.User_ID).FirstOrDefault();
                    if (user.Avatar == null)
                    {
                        user.Image = "~/Asset/img/user.png";
                    }
                    else
                    {
                        user.Image = ConvertImage(user.Avatar);
                    }
                    user.PassWord = new AccountDAO().ToHex(user.PassWord);
                    return View(user);
                
               
            }

            return RedirectToAction("Index", "UserLogin");
        }
        [HttpGet]
        public ActionResult Editnews(string IDNews)
        {
            if (Session[CommonConstants.USER_SESSION] != null || IDNews != null)
            {
                News model = db.News.Where(x => x.IDNews == IDNews).FirstOrDefault();
                var brand = db.Brand.Where(x => x.IDBrand == model.IDBrand).FirstOrDefault();

                model.nameBrand =  brand.SubCategory.Name + " " +brand.Name;
                return View(model);
            }
            return RedirectToAction("Index", "Home");
        }
        [HttpGet]
        public ActionResult EditnewsRefuse(string IDNews)
        {
            if (Session[CommonConstants.USER_SESSION] != null || IDNews == null)
            {
                News model = db.News.Where(x => x.IDNews == IDNews).FirstOrDefault();
                model.listCate = db.Category.ToList();
                TempData["listCate-edit"] = model.listCate;
                return View(model);
            }
            return RedirectToAction("Index", "Home");
        }
        public  ActionResult EditImgNews(string IDNews)
        {
            List<ImgNews> list = db.ImgNews.Where(x => x.IDNews == IDNews).ToList();
            foreach (var item in list)
            {
                item.Image =  item.ImgURL;
            }
            return PartialView(list);
        }
        [HttpGet]
        public ActionResult createOfNews()
        {
            string msg = "";
            if (Session[CommonConstants.USER_SESSION] != null)
            {
                UserSession User = (UserSession)Session[CommonConstants.USER_SESSION];
                Users user = db.Users.Where(x => x.IDUser == User.User_ID).FirstOrDefault();
                List<News> listnews = db.News.Where(x => x.IDUser == user.IDUser).ToList();
              
                if (listnews.Count <100)
                {
                    News news = new News();
                    news.listCate = db.Category.ToList();
                    TempData["listCate"] = news.listCate;
                    return View(news);
                }
                else
                {
                    msg = "True";
                    return Json(msg,JsonRequestBehavior.AllowGet);
                }
            }
            msg = "False";
            return Json(msg, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult BoxSave(string IDUser)
        {
            if (Session[CommonConstants.USER_SESSION] != null)
            {
                var boxsave = db.BoxSave.Where(x => x.IDUser == IDUser).ToList();
                foreach (var item in boxsave)
                {
                    ImgNews imgNews = db.ImgNews.Where(x => x.IDNews == item.IDNews).FirstOrDefault();
                    item.Image = imgNews.ImgURL;
                }
                return View(boxsave);
            }
            return RedirectToAction("Index", "UserLogin");
        }
        [HttpPost]
        public  async Task<ActionResult> Editnews(HttpPostedFileBase[] Images, News model)
        {
            if (ModelState.IsValid)
            {
                var listImg = db.ImgNews.Where(x => x.IDNews == model.IDNews).ToList();
               
                if (model.listImage.Count > 0)
                {
                    foreach (var item in listImg)
                    {
                        bool temp = false;
                        foreach (var img in model.listImage)
                        {
                            if (!img.Contains("blob:") && item.ImgURL == img)
                            {
                                temp = true;
                            }
                        }
                        if (temp == false)
                        {
                            db.ImgNews.Remove(item);
                            db.SaveChanges();
                            await Task.Run(() => ConnectFireBase.Delete(item.NameImage));
                        }
                    }
                }
               
                if (Images.Length > 0 && Images[0] != null)
                {
                    foreach (var item in Images)
                    {
                        FileStream steam;
                        if (item.ContentLength > 0)
                        {
                            string path = Path.Combine(Server.MapPath("~/Content/images/"), item.FileName);
                            item.SaveAs(path);
                            steam = new FileStream(Path.Combine(path), FileMode.Open);
                            Task.WaitAll(Task.Run(()=>ConnectFireBase.Upload(steam, item.FileName, model, db)));


                        }
                    }
                }
                NewsDAO Editnews = new NewsDAO();
                Editnews.EditNews(model);                         
                ViewBag.status = "True";
                return View(model);
            }
            ViewBag.status = "False";
            return View(model);
        }
    
        [HttpPost]
        public ActionResult EditnewsRefuse(HttpPostedFileBase[] Images, News model)
        {
            if (ModelState.IsValid)
            {
                NewsDAO Editnews = new NewsDAO();
                Editnews.EditnewsRefuse(Images, model);
                model.listCate = db.Category.ToList();
                ViewBag.status = "True";
                return View(model);
            }
            model.listCate = (List<Category>)TempData["listCate-edit"];
            if (Images == null && model.listImage.Count==0)
            {
                ViewBag.ErrorImg = "False";
            }
            ViewBag.status = "False";
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async  Task<ActionResult> createOfNews(HttpPostedFileBase[] Image, News news)
        {
            if(Image != null)
            {
                if (ModelState.IsValid)
                {
                   
                    UserSession User = (UserSession)Session[CommonConstants.USER_SESSION];
                    news.IDUser = User.User_ID;
                    news.IDNews = db.Database.SqlQuery<string>("select dbo.fn_getRandom_Value()").FirstOrDefault();
                    news.Time = DateTime.Now;
                    news.Status = 2;
                    db.News.Add(news);
                    db.SaveChanges();
                    
                    foreach (var item in Image)
                    {

                        FileStream steam;
                        if (item.ContentLength > 0)
                        {
                            string path = Path.Combine(Server.MapPath("~/Content/images/"), item.FileName);
                            item.SaveAs(path);
                            steam = new FileStream(Path.Combine(path), FileMode.Open);
                            await Task.Run(() => ConnectFireBase.Upload(steam, item.FileName, news, db));
                        }
                    }

RaoVat/Views/UserProfile/BoxSave.cshtml
@model IEnumerable<RaoVat.Models.BoxSave>
@using System.Globalization
@{
    ViewBag.Title = "BoxSave";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="grid">
    <div class="info__user-news">
        <h1 class="info__user-news-header">
            Tin Rao Yêu Thích -
            <span class="info__user-news-subheader"> @Model.ToList().Count Tin</span>
        </h1>
        @if (Model.ToList().Count == 0)
        {
            <div class="info__user-news-nothing" style="padding-bottom:32px;">
                <img src="~/Asset/img/binoculars.PNG" alt="" class="info__user-news-nothing-img">
                <div class="info__user-news-nothing-text">Không tìm thấy tin rao yêu thích nào của bạn.</div>
            </div>
        }
        else
        {
            <div class="info__user-news-detail">
                <ul class="news__havenews-list">
                    @foreach (var item in Model)
                    {
                        <li class="news__havenews-item">
                            <a href="@Url.Action("InfoNews","News",new { IDNews=item.IDNews })" class="news__havenews-link">
                                <div class="news__havenews-border-img">
                                    <img src="@Url.Content(item.Image)" alt="" class="news__havenews-img">
                                </div>
                                <div class="news__havenews-info">
                                    <div class="news__havenews-name">@item.News.Name</div>
                                    @{ CultureInfo culture = new CultureInfo("vi-VN");
                                        var price = String.Format(culture, "{0:N0}", item.News.Price);
                                    }
                                <div class="news__havenews-price">@price VNĐ</div>
                                </div>
                            </a>
                            <div class="news__havenews-subinfo">
                                <div style="display: inline-block;">
                                    @if (item.News.Type == true)
                                    {
                                        <span class="news__havenews-subinfo-text">
                                            <i class="fas fa-store icon-news-store"></i>
                                            Cửa hàng
                                        </span>
                                    }
                                    else
                                    {
                                        <span class="news__havenews-subinfo-text">
                                            <i class="fas fa-user icon-news-store"></i>
                                            Cá Nhân
                                        </span>
                                    }
                                    <i style="border-right: 1px solid var(--border--color);  margin:0px 4px ;"></i>
                                    <span class="news__havenews-subinfo-text">@item.News.Time</span>
                                </div>
                                <div style="float:right;">
                                    @{Html.RenderAction("WishList", "Home", new { IDNews = item.IDNews });}
                                </div>                        
                            </div>
                        </li>
                    }

                </ul>
            </div>
        }
    </div>
</div>
<link href="~/Asset/css/toastr.min.css" rel="stylesheet">
<script src="~/Asset/js/script.js"></script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>

<script src="~/Asset/js/toastr.min.js"></script>
<script>
    $('.home-product-item__like').click(function (e) {

            var data = $(this).attr("id");
            $.ajax({
                dataType:"Html",
                type: "post",
                url: '@Url.Action("AddWishList", "Home")',
                data: {IDNews: data},
                success: function (result) {
                    if (result == '""') {
                        window.location.href = "/UserLogin";
                    }
                    else {
                        if (result == '"True"') {
                            $('#' + data).find('i').removeClass('far fa-heart');
                            $('#' + data).find('i').addClass('fas fa-heart');
                            toastr.success('Lưu Tin Rao Thành Công','Thông Báo');
                        }
                        else {
                            $('#' + data).find('i').removeClass('fas fa-heart');
                            $('#' + data).find('i').addClass('far fa-heart');
                            toastr.error('Tin rao đã được hủy', 'Thông Báo');
                        }
                    }

                }
            })
        })
    //e.preventDefault();
    //console.log($(this).attr("id"));
    //if ($(this).find('i').hasClass('far fa-heart')) {
    //    $(this).find('i').removeClass('far fa-heart');
    //    $(this).find('i').addClass('fas fa-heart');
    //    alert("Lưu Tin Thành Công");
    //}
    //else {
    //    $(this).find('i').removeClass('fas fa-heart');
    //    $(this).find('i').addClass('far fa-heart');
    //    alert("Tin lưu đã được hủy");
    //}
    toastr.options = {
        "closeButton": true,
        "debug": false,
        "newestOnTop": false,
        "progressBar": false,
        "positionClass": "toast-bottom-center",
        "preventDuplicates": false,
        "onclick": null,
        "showDuration": "300",
        "hideDuration": "1000",
        "timeOut": "3000",
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    }

</script>

RaoVat/Views/UserProfile/Index.cshtml
@model RaoVat.Models.Users
<style>
    .delete-news-btn:hover {
        opacity: 0.6;
    }
</style>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    var session = (RaoVat.Common.UserSession)Session[RaoVat.Common.CommonConstants.USER_SESSION];
}

<div class="grid">
    <div class="info__user-personal">
        <div class="info__user-personal-main">
            <img src="@Url.Content(Model.Image)" alt="" class="info__user-personal-img" style="object-fit:cover;">
            <div style="margin-left:12px;">
                <h1 class="info__user-personal-name"> @Html.DisplayFor(model => model.FullName)</h1>
                <a href="@Url.Action("EditInfo", "UserProfile", new {IDUser=session.User_ID},null)" class="info__user-personal-btn">
                    Chỉnh sửa trang cá nhân
                </a>
            </div>
        </div>
        <div class="info__user-personal-sub">
            <ul class="info__user-personal-sub-list">
                <li class="info__user-personal-sub-list-item">
                    <i class="far fa-star user-personal-icon"></i>
                    <span>Đánh giá: Chưa có đánh giá</span>
                </li>
                <li class="info__user-personal-sub-list-item">
                    <i class="far fa-map user-personal-icon"></i>
                    @Html.DisplayFor(model => model.Address)
                </li>
                <li class="info__user-personal-sub-list-item">
                    <i class="far fa-calendar user-personal-icon"></i>
                    @Html.DisplayFor(model => model.DateCreate, "{0:dd-MM-yyyy}")
                </li>
            </ul>
        </div>
        <div class="info__user-personal-sub">
            <ul class="info__user-personal-sub-list">
                <li class="info__user-personal-sub-list-item">
                    <a href="@Url.Action("BoxSave","UserProfile",new { IDUser=Model.IDUser })" class="info__user-personal-sub-item-link">
                        <i class="fab fa-gratipay user-personal-sub-icon heart"></i>
                        <span>Xem tin đã lưu</span>
                    </a>
                </li>
                <li class="info__user-personal-sub-list-item">
                    <a href="" class="info__user-personal-sub-item-link">
                        <i class="fas fa-book-open user-personal-sub-icon history"></i>
                        <span>Xem lịch sử giao dịch</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="info__user-news" id="news-of-user">
        @{Html.RenderAction("newsOfUser", "News");}
    </div>
    <div class="info__user-news" id="news-of-refuse">
        @{Html.RenderAction("newsRefuse", "News");}
    </div>
</div>
<div class="modal" id="eventclick-modal" style="z-index:999;">
    <div class="modal__overplay" onclick="closeModal()">
    </div>
    <div class="modal__body">
        <div id="Message-Comfirm">
            <h1 class="message-header">Thông Báo</h1>
            <p class="message-text">Bạn có chắc rằng muốn xóa tin rao ?</p>
            <div style="padding-top: 8px; padding-bottom: 32px;">
                <button class="btn btn-primary comfirm-btn" onclick="ComfirmDelete()"> Xác Nhận</button>
                <button class="btn btn-primary cancel-btn" style="width:100.83px;" onclick="closeModal()"> Hủy</button>
            </div>

        </div>
    </div>
</div>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Asset/js/deletenews.js"></script>
<script src="~/Asset/js/deleterefuse.js"></script>

RaoVat/Views/UserProfile/InfoOtherUser.cshtml
@model RaoVat.Models.Users
@{
    ViewBag.Title = "InfoOtherUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="grid">
    <div class="info__user-personal">
        <div class="info__user-personal-main">
            <img src="@Url.Content(Model.Image)" alt="" class="info__user-personal-img" id="previewImage">
            <div>
                <h1 class="info__user-personal-name">@Html.DisplayFor(model => model.FullName)</h1>
            </div>
        </div>
        <div class="info__user-personal-sub">
            <ul class="info__user-personal-sub-list">
                <li class="info__user-personal-sub-list-item">
                    <i class="far fa-star user-personal-icon"></i>
                    <span>Đánh giá: Chưa có đánh giá</span>
                </li>
                <li class="info__user-personal-sub-list-item">
                    <i class="far fa-map user-personal-icon"></i>
                    <span>
                        Địa chỉ:
                        @Html.DisplayFor(model => model.Address)
                    </span>
                </li>
                <li class="info__user-personal-sub-list-item">
                    <i class="far fa-calendar user-personal-icon"></i>
                    <span>
                        Ngày tham gia:
                        @Html.DisplayFor(model => model.DateCreate)
                    </span>
                </li>
            </ul>
        </div>
    </div>
    <div class="info__user-news">
        @{ Html.RenderAction("NewsOfOtherUser", "News", new { IDUser = Model.IDUser });}
    </div>
</div>
<div class="modal" id="eventclick-modal" style="z-index:999;">
    <div class="modal__overplay" onclick="closeModal()">
    </div>
    <div class="image-body" id="">
        <div id="image-zoom">
            <img src="@Url.Content(Model.Image)"
                 alt=""  style="object-fit: cover; width: 500px; height: 500px;border-radius:50%;">
        </div>
    </div>
</div>
<script src="~/Asset/js/zoomimage.js"></script>
<link href="~/Asset/css/toastr.min.css" rel="stylesheet">
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Asset/js/toastr.min.js"></script>
<script src="~/Asset/js/wishlist.js"></script>